CREATE TABLE IF NOT EXISTS dii_replay_issue (
    id                          BIGINT AUTO_INCREMENT PRIMARY KEY,
    source_sheet                VARCHAR(64)  NOT NULL,
    group_name                  VARCHAR(32)  NOT NULL,
    is_sandbox                  TINYINT(1)   NOT NULL,
    row_order                   INT          NOT NULL,

    domain                      VARCHAR(64),
    sequence_no                 VARCHAR(32),
    batch_no                    VARCHAR(128),
    transaction_code            VARCHAR(64),
    transaction_name            VARCHAR(256),
    issue_level                 VARCHAR(64),
    registered_date             VARCHAR(64),
    field_name                  VARCHAR(512),
    issue_description           MEDIUMTEXT,
    transaction_owner           VARCHAR(128),
    issue_type                  VARCHAR(128),
    initial_analysis            MEDIUMTEXT,
    final_solution              MEDIUMTEXT,
    resolved_date               VARCHAR(64),
    cooperation_group           VARCHAR(256),
    resolver                    VARCHAR(128),
    serial_no                   VARCHAR(512),
    data_repair_date            VARCHAR(64),
    remark                      MEDIUMTEXT,
    affected_transaction_count  VARCHAR(32),
    issue_id                    VARCHAR(64),
    issue_key                   VARCHAR(1024),
    historical_occurrence_count VARCHAR(32),
    first_occurrence_date       VARCHAR(64),
    last_occurrence_date        VARCHAR(64),
    imported_at                 DATETIME NOT NULL,

    INDEX idx_replay_group_sandbox (group_name, is_sandbox),
    INDEX idx_replay_level (issue_level),
    INDEX idx_replay_type (issue_type),
    INDEX idx_replay_transaction (transaction_code),
    INDEX idx_replay_issue_id (issue_id),
    INDEX idx_replay_order (group_name, is_sandbox, row_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='并行回放问题清单全量快照';
