CREATE TABLE IF NOT EXISTS dii_replay_daily_summary (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_no VARCHAR(128) NOT NULL COMMENT '规范化后的回放批次',
    domain VARCHAR(64) NOT NULL COMMENT '领域',
    covered_interface_count BIGINT COMMENT '覆盖528接口',
    sent_transaction_count BIGINT COMMENT '发送交易量',
    both_fail_same_code BIGINT COMMENT '二者均失败响应码一致',
    both_success BIGINT COMMENT '二者均成功',
    code_ignored BIGINT COMMENT '响应码忽略',
    match_pass_rate DECIMAL(12,8) COMMENT '比对通过率',
    issue_total BIGINT COMMENT '问题总数',
    source_row INT NOT NULL COMMENT 'Excel原始行号',
    raw_json JSON COMMENT '原始解析值',
    imported_at DATETIME NOT NULL,
    INDEX idx_replay_daily_summary_batch (batch_no),
    INDEX idx_replay_daily_summary_domain (batch_no, domain)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回放日报汇总信息下半区明细';

CREATE TABLE IF NOT EXISTS dii_replay_interface_comparison (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_no VARCHAR(128) NOT NULL COMMENT '规范化后的回放批次',
    row_type VARCHAR(16) NOT NULL COMMENT 'DETAIL或TOTAL',
    transaction_code VARCHAR(128),
    s_code VARCHAR(512),
    transaction_description VARCHAR(512),
    developer VARCHAR(512),
    bank_owner VARCHAR(512),
    domain VARCHAR(128),
    sent_transaction_count BIGINT,
    c528_success_ccbs_fail BIGINT,
    c528_fail_ccbs_success BIGINT,
    both_fail_same_code BIGINT,
    both_fail_diff_code BIGINT,
    both_success BIGINT,
    code_ignored BIGINT,
    transaction_success_rate DECIMAL(12,8),
    match_pass_rate DECIMAL(12,8),
    c528_avg_duration DECIMAL(18,6),
    ccbs_avg_duration DECIMAL(18,6),
    source_row INT NOT NULL,
    raw_json JSON,
    imported_at DATETIME NOT NULL,
    INDEX idx_replay_interface_batch (batch_no),
    INDEX idx_replay_interface_type (batch_no, row_type),
    INDEX idx_replay_interface_tx (batch_no, transaction_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回放接口比对明细及合计';

CREATE TABLE IF NOT EXISTS dii_replay_coverage_summary (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_no VARCHAR(128) NOT NULL COMMENT '规范化后的回放批次',
    row_type VARCHAR(16) NOT NULL COMMENT 'DETAIL或TOTAL',
    business_domain VARCHAR(128),
    full_transaction_count BIGINT,
    sent_count BIGINT,
    unsent_count BIGINT,
    excluded_count BIGINT,
    recent_transaction_count BIGINT,
    pending_analysis_count BIGINT,
    coverage_rate DECIMAL(12,8),
    source_row INT NOT NULL,
    raw_json JSON,
    imported_at DATETIME NOT NULL,
    INDEX idx_replay_coverage_summary_batch (batch_no),
    INDEX idx_replay_coverage_summary_type (batch_no, row_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回放交易覆盖领域汇总及合计';

CREATE TABLE IF NOT EXISTS dii_replay_coverage_detail (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_no VARCHAR(128) NOT NULL COMMENT '规范化后的回放批次',
    transaction_code VARCHAR(128),
    transaction_description VARCHAR(512),
    business_domain VARCHAR(128),
    s_code VARCHAR(512),
    related_code VARCHAR(512),
    replay_required VARCHAR(64),
    latest_transaction_date DATE,
    sent_transaction_count BIGINT,
    coverage_status VARCHAR(128),
    unsent_reason VARCHAR(1024),
    developer VARCHAR(512),
    bank_owner VARCHAR(512),
    source_row INT NOT NULL,
    raw_json JSON,
    imported_at DATETIME NOT NULL,
    INDEX idx_replay_coverage_detail_batch (batch_no),
    INDEX idx_replay_coverage_detail_tx (batch_no, transaction_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回放交易覆盖明细';
